name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Removed 18.x because your dependencies require Node 20+
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # enable npm caching keyed by package.json so installs are faster
        cache: 'npm'
        cache-dependency-path: package.json

    - name: Install dependencies
      run: |
        # Prefer a clean install if a lockfile exists, otherwise fall back to npm install
        npm ci --prefer-offline --no-audit --progress=false || npm install --no-audit --progress=false

    - name: Build (production)
      run: |
        # Use the project's build script to ensure webpack config is respected
        npm run build

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        # make artifact name unique per run/matrix to avoid 409 Conflict when the same
        # workflow job attempts to upload an artifact with the same name more than once
        name: webpack-dist-${{ matrix.node-version }}-${{ github.run_id }}
        path: dist/
